### ISSUE TITLE
Set up Webpack

### ISSUE THREAD

**Issue by malinatran** [sanctuarycomputer/moti#1]

**Comment by malinatran** [comment]
CSS precompiler

**Comment by sepowitz** [comment]
Resources used: 

#### General setup

http://jmfurlott.com/tutorial-setting-up-a-single-page-react-web-app-with-react-router-and-webpack/

#### Adding SASS build step

http://www.jonathan-petitcolas.com/2015/05/15/howto-setup-webpack-on-es6-react-application-with-sass.html
